### ISSUE TITLE
Integrate the news API in the project

### ISSUE THREAD

**Issue by timothyrusso** [chingu-voyages/v43-tier2-team-13#58]

**Comment by Saga-sanga** [comment]
In the current implementation, the news component updates with the selected coin. E.g. if Bitcoin is selected it shows news related to Bitcoin.

Pros:
- Doesn't require login to display news.
- Intuitive user experience.

Cons:
- Requires more queries to the server
- Less Personalised news. (But the API limits the free tier to only 10 news per request anyways)
